BlogCore/Areas/Admin/Controllers/ArticlesController.cs
using BlogCore.Data;
using BlogCore.DataAccess.Data.Repository.IRepository;
using BlogCore.Models;
using BlogCore.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BlogCore.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ArticlesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWorkUnity _workUnity;

        public ArticlesController(ApplicationDbContext context, IWorkUnity workUnity)
        {
            _context = context;
            _workUnity = workUnity;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            ArticleVM articleVM = new ArticleVM()
            {
                Article = new BlogCore.Models.Article(),
                ListaCategorias = _workUnity.Categoria.GetListCategories()
        };
            return View(articleVM);
        }

        /*[HttpPost]
        public IActionResult Create(Article article)
        {
            return View(article);
        }*/

        #region Lamadas a la Api
        [HttpGet]
        public IActionResult GetAll()
        {
            //opción 1
            return Json(new { data = _workUnity.Articulo.GetAll() });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _workUnity.Articulo.Get(id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error al borrar la Categoria" });

            }

            _workUnity.Articulo.Remove(objFromDb);
            _workUnity.Save();
            return Json(new { success = true, message = "Categoría borrada correctamente" });
        }

        #endregion

    }
}

BlogCore/Areas/Admin/Controllers/CategoriesController.cs
using BlogCore.Data;
using BlogCore.DataAccess.Data.Repository.IRepository;
using BlogCore.Models;
using BlogCore.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BlogCore.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoriesController : Controller
    {

        private readonly IWorkUnity _workcontainer;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public CategoriesController(IWorkUnity workcontainer, IWebHostEnvironment webHostEnvironment)
        {
            _workcontainer = workcontainer;
            _hostingEnvironment = webHostEnvironment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ArticleVM articleVM)
        {
            if(ModelState.IsValid)
            {
                string mainRoot = _hostingEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;

                if (articleVM.Article.Id == 0)
                {
                    // Nuevo Artículo
                    string fileName = Guid.NewGuid().ToString();
                    // ruta principal = wwwroot
                    // wwwroot/images/articles
                    var uploads = Path.Combine(mainRoot, @"images/articles");
                    var extensions = Path.GetExtension(files[0].FileName);

                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extensions), FileMode.Create))
                    {
                        files[0].CopyTo(fileStreams);
                    }

                    _workcontainer.Articulo.Add(articleVM.Article);
                    _workcontainer.Save();

                    return RedirectToAction(nameof(Index));
                }
            }

            articleVM.ListaCategorias = _workcontainer.Categoria.GetListCategories();

            return View(articleVM);
        }

        #region Lamadas a la Api
        [HttpGet]
        public IActionResult GetAll()
        {
            //opción 1
            return Json(new { data = _workcontainer.Categoria.GetAll() });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _workcontainer.Categoria.Get(id);
            if(objFromDb == null)
            {
                return Json(new { success = false, message = "Error al borrar la Categoria" });

            }

            _workcontainer.Categoria.Remove(objFromDb);
            _workcontainer.Save();
            return Json(new { success = true, message="Categoría borrada correctamente" });
        }

        #endregion
    }
}

BlogCore/Areas/Client/Controllers/HomeController.cs
using BlogCore.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BlogCore.Areas.Client.Controllers
{
    [Area("Client")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BlogCore/Controllers/HomeController.cs
using BlogCore.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BlogCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BlogCore/Areas/Admin/Views/Articles/Create.cshtml
@model BlogCore.Models.ViewModels.ArticleVM

@{
    ViewData["Title"] = "Crear Articulo";
}

<br />
<br />
<h3 class="text-center">Crear un nuevo Articulo</h3>
<form method="POST" asp-action="Create" enctype="multipart/form-data">
    <div class="row px-2 offset-1 border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="col-10 offset-1 mt-4">
            <div class="form-group row">
                <div class="col-5">
                    <label class="col-4">
                        <label asp-for="Article.Name"></label>
                    </label>
                </div>
                <div class="col-7">
                    <input asp-for="Article.Name" class="form-control" placeholder="Ingrese el nombre del Art&iacute;culo" />
                    <span asp-validation-for="Article.Name" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row mt-2">
                <div class="col-5">
                    <label class="col-4">
                        <label asp-for="Article.Description"></label>
                    </label>
                </div>
                <div class="col-7">
                    <input asp-for="Article.Description" class="form-control" placeholder="Agregue una Descripci&oacute;n del Artículo" />
                    <span asp-validation-for="Article.Description" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row mt-2">
                <div class="col-5">
                    <label class="col-4">
                        <label asp-for="Article.CategoryId">Categor&iacute;a</label>
                    </label>
                </div>
                <div class="col-7">
                    @Html.DropDownListFor(m => m.Article.CategoryId, Model.ListaCategorias, "-Porfavor selecciona una categoría",
                    new {@class = "form-control"}
                    )
                </div>
            </div>

            <div class="form-group row mt-2">
                <div class="col-5">
                    <label class="col-4">
                        <label asp-for="Article.UrlImage">Imagen</label>
                    </label>
                </div>
                <div class="col-7">
                    <input type="file" name="files" id="uploadFile" class="form-control" />
                </div>
            </div>

            <div class="form-group row">
                <div class="col-8">
                    <br />
                    <partial name="_ViewCreateBack" />
                </div>

            </div>
        </div>
    </div>
</form>

BlogCore/Areas/Admin/Views/Articles/Index.cshtml
@{
    ViewData["Title"] = "Articulos";
}
<div class="container mt-4">
    <div class="row">
        <div class="col-8">
            <h2 class="text-primary">Lista de Artículos</h2>
        </div>
        <div class="col-4 text-right">
            <a asp-action="Create" class="btn btn-primary"><i class="fas fa-plus"></i> Crear Nuevo Artículo</a>
        </div>
    </div>

    <br />
    <br />

    <table id="tblArticulos" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Categor&iacute;a</th>
                <th>Fecha de Creaci&oacute;n</th>
                <th>Acciones</th>
            </tr>
        </thead>
    </table>

</div>

@section Scripts {

    <script src="~/js/article.js"></script>
}

BlogCore/Areas/Admin/Views/Categories/Create.cshtml
@model BlogCore.Models.Category

@{
    ViewData["Title"] = "Crear Categoria";
}

<br />
<br />
<h3 class="text-center">Crear una nueva Categoria</h3>
<form method="POST" asp-action="Create">
    <div class="row px-2 offset-1 border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="col-10 offset-1 mt-4">
            <div class="form-group row">
                <div class="col-5">
                    <label class="col-4">
                        <label asp-for="Name"></label>
                    </label>
                </div>
                <div class="col-7">
                    <input asp-for="Name" class="form-control" placeholder="Ingrese el nombre de la categor&iacute;a"/>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>

            <br />

            <div class="form-group row">
                <div class="col-5">
                    <label class="col-4">
                        <label asp-for="Order"></label>
                    </label>
                </div>
                <div class="col-7">
                    <input asp-for="Order" class="form-control" placeholder="Ingrese el orden de visualizaci&oacute;n"/>
                    <span asp-validation-for="Order" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-8">
                    <br />
                    <partial name="_ViewCreateBack" />
                </div>
                    
            </div>
        </div>
    </div>
</form>

BlogCore/Areas/Admin/Views/Categories/Edit.cshtml
@model BlogCore.Models.Category

@{
    ViewData["Title"] = "Editar Categoria";
}

<br />
<br />
<h3 class="text-center">Crear una nueva Categoria</h3>
<form method="POST" asp-action="Edit">
    <div class="row px-2 offset-1 border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="col-10 offset-1 mt-4">
            <div class="form-group row">
                <div class="col-5">
                    <label class="col-4">
                        <label asp-for="Name"></label>
                    </label>
                </div>
                <div class="col-7">
                    <input asp-for="Name" class="form-control" placeholder="Ingrese el nombre de la categor&iacute;a" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>

            <br />

            <div class="form-group row">
                <div class="col-5">
                    <label class="col-4">
                        <label asp-for="Order"></label>
                    </label>
                </div>
                <div class="col-7">
                    <input asp-for="Order" class="form-control" placeholder="Ingrese el orden de visualizaci&oacute;n" />
                    <span asp-validation-for="Order" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col">
                    <br />
                    <button type="submit" class="btn btn-primary form-control" asp-route="@Model.Id">Actualizar</button>
                </div>
                <div class="col">
                    <br />
                    <a asp-action="Index" class="btn btn-success form-control">Volver a la Lista</a>
                </div>

            </div>
        </div>
    </div>
</form>

BlogCore/Areas/Admin/Views/Categories/Index.cshtml
@{
    ViewData["Title"] = "Categorias";
}
<div class="container mt-4">
    <div class="row">
        <div class="col-8">
            <h2 class="text-primary">Lista de Categorias</h2>
        </div>
        <div class="col-4 text-right">
            <a asp-action="Create" class="btn btn-primary"><i class="fas fa-plus"></i> Crear Nueva Categoría</a>
        </div>
    </div>

    <br />
    <br />

    <table id="tblCategorias" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Orden</th>
                <th>Acciones</th>
            </tr>
        </thead>
    </table>

</div>

@section Scripts {
    
    <script src="~/js/category.js"></script>
}

BlogCore/Areas/Client/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BlogCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlogCore.styles.css" asp-append-version="true" />

    <!-- Plugins Frontend -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/themes/base/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Client" asp-controller="Home" asp-action="Index">Blog Core</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor04" aria-controls="navbarColor04" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor04">
                    <ul class="navbar-nav me-auto">
      
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Contenidos</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Categories" asp-action="Index">Categor&iacute;as</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Articles" asp-action="Index">Art&iacute;culos</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Sliders" asp-action="Index">Sliders</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Users" asp-action="Index">Usuarios</a>
                            </div>
                        </li>
                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BlogCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Plugins Frontend -->

    <script type="text/javascript" src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/3.2.1/jquery.serializejson.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/0f48d8c00d.js" crossorigin="anonymous"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BlogCore/Views/Shared/_ViewCreateBack.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">Crear</button>
    </div>
    &nbsp;
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Volver</a>
    </div>
</div>